# Generated by Django 5.0.4 on 2024-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
